-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-28 22:32:30 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE athletes (
    id            INTEGER,
    name          VARCHAR2(4000),
    nationality   VARCHAR2(4000),
    sex           VARCHAR2(4000),
    dob           DATE,
    height        NUMBER,
    weight        NUMBER,
    sport         VARCHAR2(4000),
    gold          INTEGER,
    silver        BLOB
);

ALTER TABLE athletes ADD CONSTRAINT athletes_sport_un UNIQUE ( sport );

ALTER TABLE athletes ADD CONSTRAINT athletes_nationality_un UNIQUE ( nationality );

CREATE TABLE countries (
    country                VARCHAR2(4000),
    code                   VARCHAR2(4000),
    population             NUMBER,
    gpd_per_capita         NUMBER,
    athletes_nationality   VARCHAR2(4000) NOT NULL
);

CREATE UNIQUE INDEX countries__idx ON
    countries (
        athletes_nationality
    ASC );

ALTER TABLE countries ADD CONSTRAINT countries_code_un UNIQUE ( code );

CREATE TABLE events (
    id               INTEGER,
    sport            VARCHAR2(4000),
    discipline       VARCHAR2(4000),
    name             VARCHAR2(4000),
    sex              VARCHAR2(4000),
    venues           VARCHAR2(4000),
    athletes_sport   VARCHAR2(4000) NOT NULL
);

CREATE UNIQUE INDEX events__idx ON
    events (
        athletes_sport
    ASC );

ALTER TABLE events ADD CONSTRAINT events_sport_un UNIQUE ( sport );

ALTER TABLE countries
    ADD CONSTRAINT countries_athletes_fk FOREIGN KEY ( athletes_nationality )
        REFERENCES athletes ( nationality );

ALTER TABLE events
    ADD CONSTRAINT events_athletes_fk FOREIGN KEY ( athletes_sport )
        REFERENCES athletes ( sport );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             3
-- CREATE INDEX                             2
-- ALTER TABLE                              6
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
